### ISSUE TITLE
Move config into a separate file

### ISSUE THREAD

**Issue by kirjatoukka** [kirjatoukka/drakebot#1]
Currently config is hardcoded, this should be in a separate file to be loaded at startup. Or possibly an environment variable, what's easiest with Heroku?

**Comment by nickcharlton** [comment]
I think you'd want to support something like a YAML file as well as environment variables. Bit of a pain to implement though.

What needs configuring?

* [ ] server
* [ ] channels
* [ ] nick

**Comment by kirjatoukka** [comment]
Those are the main things. Plus server/nickserv password. In future other things like plugins, possibly.

The main concern I'm seeing with heroku is that I wouldn't want to commit the password, so that needs to come from somewhere other than the public repo. Basically, I need to read the docs before implementing.

**Comment by nickcharlton** [comment]
Is this (`drakebot`) the same as the one that's deployed? Or should that be a split repo?

So, functionality here, deployed version (for each channel) in a split repo?

**Comment by kirjatoukka** [comment]
Currently, this is the deployed one. That could work though.

**Comment by kirjatoukka** [comment]
On the other hand, configuration in Heroku [config vars](https://devcenter.heroku.com/articles/config-vars) seems like it would do the trick, although part of me is suspicious of putting private information in environment variables.

**Comment by nickcharlton** [comment]
There's no other way to do it though, is there?

Also you can't see them unless you're part of the Heroku app?

**Comment by kirjatoukka** [comment]
In theory environment variables for a process can be read by other processes on the same machine. (e.g., in `/proc/<pid>/environ` on Linux machines). It'd need root access though so I suppose I should assume that if someone can do so everything's doomed anyway.

**Comment by nickcharlton** [comment]
My current thought on this is to just accept environment variables; something like:

```
configure do |c|
  c.server = ENV['DRAKEBOT_SERVER'] || ''
  c.nick = ENV['DRAKEBOT_NICK'] || ''
  c.channels = ENV['DRAKEBOT_CHANNELS'] || ''
end
```

Thoughts?

**Comment by kirjatoukka** [comment]
My thought would be to load settings from a config file (if one is present/specified), then override with environment variables (if those are specified). We'd also want to fail if any of the required settings are missing (which is all of them, for now, though channels could in future be altered at runtime).

On the other hand, loading from a config file seems like low priority since Heroku is our target platform, so maybe just stick with environment variables.

**Comment by nickcharlton** [comment]
I'm going to close this off by adding initial environment support for now. I might pull some better config handling over from another project in the future.
