### ISSUE TITLE
Quote Tweets should pull out the quote tweet too.

### ISSUE THREAD

**Issue by nickcharlton** [kirjatoukka/drakebot#27]
Say you've got something like: https://twitter.com/guardianstyle/status/645967268615200768, which contains a quote around: https://twitter.com/gominokouhai/status/645749970197442560

It should do something like:

```
[ Guardian style guide on Twitter: "Yes: it's the same principle as, say, "prime minister": all lowercase, no hyphens. → pajh on Twitter: ".@guardianstyle, I'm presuming that the approved spelling is "pigfucker" with no hyphenation, right?" ]
```

Notably, it should only do this for the first tweet. Otherwise you'd get something like [this thread between Emily Maitlis and Piers Morgan][example] which goes on for ages.

[example]: https://twitter.com/maitlis/status/644259260545806336

**Comment by kirjatoukka** [comment]
- if the URL in the title (i.e., in the tweet text) is a link to a tweet, add it to the end of the queue
- might need to replace the `each` loop with a `while` loop? i don't know how lists behave if you append to them while iterating over them.
- need to add a `recurse` parameter, defaulting to true, to ensure that it only happens once.
